version: '3'
services:
  dev_env:
    build: 
      context: ./dev_env
      args:
        LAB_LOCATION: /opt/dev_env
    ports:
    - "8888:8888"
    volumes:
    - ./dev_env:/opt/dev_env
    links:
    - db
    depends_on: 
    - db
  db:
    image: postgres:9.5.19
    restart: always
    volumes: 
      - ./postgres_db:/var/lib/postgresql/data
    environment: 
      POSTGRES_DB: studentdb
      POSTGRES_USER: student
      POSTGRES_PASSWORD: student