version: '3'
services:
  dev_env:
    build: 
      context: ./dev_env
    container_name: dev_env
    env_file: .env
    links:
    - db
    depends_on: 
    - db
  db:
    image: postgres:9.5.19
    container_name: db
    restart: always
    ports:
    - "5432:5432"
    volumes: 
      - ./postgres_db:/var/lib/postgresql/data
    env_file: .env
  dashboard:
    build:
      context: ./dashboard
    container_name: dashboard
    env_file: .env
    restart: always
    ports:
      - "8050:8050"
    links:
      - db
    depends_on: 
      - dev_env